// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"mediversebe/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Addresses{},
		&models.Doctor{},
		&models.EPrescriptions{},
		&models.Facilities{},
		&models.Patients{},
		&models.Payments{},
		&models.Poli{},
		&models.Reservations{},
		&models.Roles{},
		&models.Schedules{},
		&models.Services{},
		&models.Users{},
	)
}
