// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
	"mediversebe/internal/controllers"
	"mediversebe/internal/models"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/doctors",
			Methods:    []string{fasthttp.MethodGet, fasthttp.MethodPost},
			Controller: &controllers.DoctorController{},
			Model:      models.Doctor{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWorldController{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/schedules",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.ScheduleControllers{},
			Model:      models.Schedules{},
		},
	})
}
