// Code generated by raiden-cli; DO NOT EDIT.
package EPrescriptions

import (
	"github.com/sev-2/raiden"
	"mediversebe/internal/models"
)

type RestController struct {
	raiden.ControllerBase
	Model models.EPrescriptions
}
